openapi: 3.0.1
info:
   title: Simples Hello
   description: Servico responde um simples hello para teste
   version: 0.0.1
   contact:
      name: "Autbank"
      url: "http://www.autbank.com.br/"
      email: "contato@autbank.com.br"
servers:
   - url: /
paths:
   /hello-kafka:
      get:
         summary: oi
         description: Manda um oi ao usuário e o mostra links úteis
         operationId: hello
         responses:
            200:
               description: Movimento incluido com sucesso
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Hello'
components:
   schemas:
      Hello:
         type: object
         properties:
            mensagem:
               type: string