DROP DATABASE IF EXISTS TF_REMESSA
CREATE DATABASE TF_REMESSA;
GO
USE TF_REMESSA;
GO

CREATE TABLE REMESSAS(
    ID BIGINT IDENTITY PRIMARY KEY,
    VALOR_REAIS DECIMAL(17,2),
    VALOR_DOLAR DECIMAL(17,2),
	COTACAO_DOLAR DECIMAL(17,2),
    STATUS VARCHAR(20),
    DATA_STATUS DATETIME
);
GO