DROP DATABASE IF EXISTS TF_BANCO
CREATE DATABASE TF_BANCO;
GO
USE TF_BANCO;
GO

CREATE TABLE CONTAS(
    ID BIGINT IDENTITY PRIMARY KEY,
    TITULAR VARCHAR(255),
    NUMERO_CONTA VARCHAR(8),
    SALDO DECIMAL(17,2)
);
GO

CREATE TABLE ENVIOS_EXTERIOR(
    ID BIGINT IDENTITY PRIMARY KEY,
    ID_REMESSA BIGINT,
    VALOR DECIMAL(17,2),
    STATUS VARCHAR(20),
    DATA_STATUS DATETIME
);
GO

CREATE TABLE TRANSFERENCIAS(
    ID BIGINT IDENTITY PRIMARY KEY,
    NUMERO_CONTA_CREDITO VARCHAR(8),
    VALOR DECIMAL(17,2),
    ID_REMESSA BIGINT,
    DATA_TRANSFERENCIA DATETIME
);
GO